import type { Metadata } from 'next'

import ServerSideProvider from '@/app/ServerSideProvider'

import './globals.css'

import { nanumSquare } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={nanumSquare.variable}>
      <body className={nanumSquare.className}>
        <ServerSideProvider>{children}</ServerSideProvider>
      </body>
    </html>
  )
}
